# Generated by Django 5.2.17 on 2026-09-04 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Ad')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Müddət (dəqiqə)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
                ('pdf_file', models.FileField(blank=True, help_text='Sınaq suallarının olduğu PDF. Yüklənəndə suallar avtomatik parse edilə bilər.', null=True, upload_to='exams/pdfs/', verbose_name='PDF faylı')),
            ],
            options={
                'verbose_name': 'İmtahan',
                'verbose_name_plural': 'İmtahanlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Başlama vaxtı')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Təhvil vaxtı')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Yekun bal')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlanıb')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.exam', verbose_name='İmtahan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Tələbə')),
            ],
            options={
                'verbose_name': 'İmtahan nəticəsi',
                'verbose_name_plural': 'İmtahan nəticələri',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Sual nömrəsi')),
                ('text', models.TextField(verbose_name='Sual mətni')),
                ('image', models.ImageField(blank=True, help_text='Düstur, qrafik və ya cədvəl kəsildikdə buraya yükləyin.', null=True, upload_to='exams/questions/', verbose_name='Sual şəkli')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='İmtahan')),
            ],
            options={
                'verbose_name': 'Sual',
                'verbose_name_plural': 'Suallar',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Hərf')),
                ('text', models.TextField(blank=True, verbose_name='Variant mətni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exams/choices/', verbose_name='Variant şəkli')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Düzgün cavab')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.question', verbose_name='Sual')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'ordering': ['letter'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_answers', to='exams.choice', verbose_name='Seçilmiş variant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='exams.question', verbose_name='Sual')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examsubmission', verbose_name='Nəticə')),
            ],
            options={
                'verbose_name': 'Tələbə cavabı',
                'verbose_name_plural': 'Tələbə cavabları',
            },
        ),
        migrations.AddConstraint(
            model_name='examsubmission',
            constraint=models.UniqueConstraint(fields=('user', 'exam'), name='unique_user_exam_submission'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('exam', 'number'), name='unique_exam_question_number'),
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('question', 'letter'), name='unique_question_choice_letter'),
        ),
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_submission_question_answer'),
        ),
    ]
