# Generated by Django 5.2.17 on 2026-09-04 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='closes_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bağlanma tarixi'),
        ),
        migrations.AddField(
            model_name='exam',
            name='opens_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Açılma tarixi'),
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_score',
            field=models.PositiveIntegerField(default=50, verbose_name='Keçid balı (%)'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Sertifikat kodu')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Verilmə tarixi')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='exams.examsubmission', verbose_name='Nəticə')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['-issued_at'],
            },
        ),
    ]
