# Generated by Django 5.2.17 on 2026-09-06 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_closes_at_exam_opens_at_exam_passing_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, unique=True, verbose_name='Əlaqə nömrəsi')),
                ('district', models.CharField(choices=[('Bakı — Binəqədi', 'Bakı — Binəqədi'), ('Bakı — Xətai', 'Bakı — Xətai'), ('Bakı — Xəzər', 'Bakı — Xəzər'), ('Bakı — Nərimanov', 'Bakı — Nərimanov'), ('Bakı — Nəsimi', 'Bakı — Nəsimi'), ('Bakı — Nizami', 'Bakı — Nizami'), ('Bakı — Pirallahı', 'Bakı — Pirallahı'), ('Bakı — Qaradağ', 'Bakı — Qaradağ'), ('Bakı — Sabunçu', 'Bakı — Sabunçu'), ('Bakı — Səbail', 'Bakı — Səbail'), ('Bakı — Suraxanı', 'Bakı — Suraxanı'), ('Bakı — Yasamal', 'Bakı — Yasamal'), ('Gəncə', 'Gəncə'), ('Sumqayıt', 'Sumqayıt'), ('Mingəçevir', 'Mingəçevir'), ('Naftalan', 'Naftalan'), ('Naxçıvan', 'Naxçıvan'), ('Şəki', 'Şəki'), ('Şirvan', 'Şirvan'), ('Yevlax', 'Yevlax'), ('Abşeron', 'Abşeron'), ('Ağcabədi', 'Ağcabədi'), ('Ağdam', 'Ağdam'), ('Ağdaş', 'Ağdaş'), ('Ağstafa', 'Ağstafa'), ('Ağsu', 'Ağsu'), ('Astara', 'Astara'), ('Babək', 'Babək'), ('Balakən', 'Balakən'), ('Beyləqan', 'Beyləqan'), ('Bərdə', 'Bərdə'), ('Biləsuvar', 'Biləsuvar'), ('Cəbrayıl', 'Cəbrayıl'), ('Cəlilabad', 'Cəlilabad'), ('Culfa', 'Culfa'), ('Daşkəsən', 'Daşkəsən'), ('Füzuli', 'Füzuli'), ('Gədəbəy', 'Gədəbəy'), ('Goranboy', 'Goranboy'), ('Göyçay', 'Göyçay'), ('Göygöl', 'Göygöl'), ('Hacıqabul', 'Hacıqabul'), ('Xaçmaz', 'Xaçmaz'), ('Xızı', 'Xızı'), ('Xocalı', 'Xocalı'), ('Xocavənd', 'Xocavənd'), ('İmişli', 'İmişli'), ('İsmayıllı', 'İsmayıllı'), ('Kəlbəcər', 'Kəlbəcər'), ('Kəngərli', 'Kəngərli'), ('Kürdəmir', 'Kürdəmir'), ('Laçın', 'Laçın'), ('Lerik', 'Lerik'), ('Lənkəran', 'Lənkəran'), ('Masallı', 'Masallı'), ('Neftçala', 'Neftçala'), ('Oğuz', 'Oğuz'), ('Ordubad', 'Ordubad'), ('Qax', 'Qax'), ('Qazax', 'Qazax'), ('Qəbələ', 'Qəbələ'), ('Qobustan', 'Qobustan'), ('Quba', 'Quba'), ('Qubadlı', 'Qubadlı'), ('Qusar', 'Qusar'), ('Saatlı', 'Saatlı'), ('Sabirabad', 'Sabirabad'), ('Salyan', 'Salyan'), ('Samux', 'Samux'), ('Siyəzən', 'Siyəzən'), ('Sədərək', 'Sədərək'), ('Şabran', 'Şabran'), ('Şahbuz', 'Şahbuz'), ('Şamaxı', 'Şamaxı'), ('Şəmkir', 'Şəmkir'), ('Şərur', 'Şərur'), ('Şuşa', 'Şuşa'), ('Tərtər', 'Tərtər'), ('Tovuz', 'Tovuz'), ('Ucar', 'Ucar'), ('Yardımlı', 'Yardımlı'), ('Zaqatala', 'Zaqatala'), ('Zəngilan', 'Zəngilan'), ('Zərdab', 'Zərdab')], max_length=64, verbose_name='Faktiki yaşadığı rayon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Tələbə profili',
                'verbose_name_plural': 'Tələbə profilləri',
            },
        ),
    ]
