# Generated by Django 5.2.17 on 2026-09-06 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_student_profile_phone_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examsubmission',
            name='unique_user_exam_submission',
        ),
        migrations.AddField(
            model_name='exam',
            name='access_mode',
            field=models.CharField(choices=[('registered', 'Yalnız qeydiyyatlı istifadəçilər'), ('public', 'İstənilən adam baxa bilər')], default='registered', max_length=20, verbose_name='Kim baxa bilər'),
        ),
        migrations.AddField(
            model_name='exam',
            name='default_points',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Sualın öz balı yoxdursa bu dəyər istifadə olunur.', null=True, verbose_name='Hər sualın ümumi balı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1, verbose_name='Cəhd sayı'),
        ),
        migrations.AddField(
            model_name='exam',
            name='show_correct_answers',
            field=models.BooleanField(default=True, verbose_name='Təhvildən sonra düzgün cavabları göstər'),
        ),
        migrations.AddField(
            model_name='exam',
            name='show_score_immediately',
            field=models.BooleanField(default=True, verbose_name='Nəticəni dərhal göstər'),
        ),
        migrations.AddField(
            model_name='exam',
            name='shuffle_choices',
            field=models.BooleanField(default=False, verbose_name='Variantları qarışdır'),
        ),
        migrations.AddField(
            model_name='exam',
            name='shuffle_questions',
            field=models.BooleanField(default=False, verbose_name='Sualları qarışdır'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='earned_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Qazanılan bal'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='max_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Maksimum bal'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(blank=True, help_text='Boşdursa imtahanın ümumi tənzimləməsindəki bal götürülür.', null=True, verbose_name='Sual balı'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, default=60, help_text='Boş buraxılsa vaxt limiti olmur.', null=True, verbose_name='Müddət (dəqiqə)'),
        ),
        migrations.AddIndex(
            model_name='examsubmission',
            index=models.Index(fields=['user', 'exam'], name='exams_exams_user_id_0160f4_idx'),
        ),
    ]
