# Generated by Django 5.2.17 on 2026-09-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_subjects_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='baku_district',
            field=models.CharField(blank=True, choices=[('Binəqədi', 'Binəqədi'), ('Xətai', 'Xətai'), ('Xəzər', 'Xəzər'), ('Nərimanov', 'Nərimanov'), ('Nəsimi', 'Nəsimi'), ('Nizami', 'Nizami'), ('Pirallahı', 'Pirallahı'), ('Qaradağ', 'Qaradağ'), ('Sabunçu', 'Sabunçu'), ('Səbail', 'Səbail'), ('Suraxanı', 'Suraxanı'), ('Yasamal', 'Yasamal')], max_length=64, verbose_name='Bakı rayonu'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('Bakı', 'Bakı'), ('Gəncə', 'Gəncə'), ('Sumqayıt', 'Sumqayıt'), ('Mingəçevir', 'Mingəçevir'), ('Naftalan', 'Naftalan'), ('Naxçıvan', 'Naxçıvan'), ('Şəki', 'Şəki'), ('Şirvan', 'Şirvan'), ('Yevlax', 'Yevlax'), ('Abşeron', 'Abşeron'), ('Ağcabədi', 'Ağcabədi'), ('Ağdam', 'Ağdam'), ('Ağdaş', 'Ağdaş'), ('Ağstafa', 'Ağstafa'), ('Ağsu', 'Ağsu'), ('Astara', 'Astara'), ('Babək', 'Babək'), ('Balakən', 'Balakən'), ('Beyləqan', 'Beyləqan'), ('Bərdə', 'Bərdə'), ('Biləsuvar', 'Biləsuvar'), ('Cəbrayıl', 'Cəbrayıl'), ('Cəlilabad', 'Cəlilabad'), ('Culfa', 'Culfa'), ('Daşkəsən', 'Daşkəsən'), ('Füzuli', 'Füzuli'), ('Gədəbəy', 'Gədəbəy'), ('Goranboy', 'Goranboy'), ('Göyçay', 'Göyçay'), ('Göygöl', 'Göygöl'), ('Hacıqabul', 'Hacıqabul'), ('Xaçmaz', 'Xaçmaz'), ('Xızı', 'Xızı'), ('Xocalı', 'Xocalı'), ('Xocavənd', 'Xocavənd'), ('İmişli', 'İmişli'), ('İsmayıllı', 'İsmayıllı'), ('Kəlbəcər', 'Kəlbəcər'), ('Kəngərli', 'Kəngərli'), ('Kürdəmir', 'Kürdəmir'), ('Laçın', 'Laçın'), ('Lerik', 'Lerik'), ('Lənkəran', 'Lənkəran'), ('Masallı', 'Masallı'), ('Neftçala', 'Neftçala'), ('Oğuz', 'Oğuz'), ('Ordubad', 'Ordubad'), ('Qax', 'Qax'), ('Qazax', 'Qazax'), ('Qəbələ', 'Qəbələ'), ('Qobustan', 'Qobustan'), ('Quba', 'Quba'), ('Qubadlı', 'Qubadlı'), ('Qusar', 'Qusar'), ('Saatlı', 'Saatlı'), ('Sabirabad', 'Sabirabad'), ('Salyan', 'Salyan'), ('Samux', 'Samux'), ('Siyəzən', 'Siyəzən'), ('Sədərək', 'Sədərək'), ('Şabran', 'Şabran'), ('Şahbuz', 'Şahbuz'), ('Şamaxı', 'Şamaxı'), ('Şəmkir', 'Şəmkir'), ('Şərur', 'Şərur'), ('Şuşa', 'Şuşa'), ('Tərtər', 'Tərtər'), ('Tovuz', 'Tovuz'), ('Ucar', 'Ucar'), ('Yardımlı', 'Yardımlı'), ('Zaqatala', 'Zaqatala'), ('Zəngilan', 'Zəngilan'), ('Zərdab', 'Zərdab')], max_length=64, verbose_name='Şəhər / bölgə'),
        ),
    ]
